import test from 'node:test'
import assert from 'node:assert/strict'

import { COMPACTION_MODES } from '../../src/main/chat/continuity/compaction-mode-contract.mjs'
import {
  buildOpenAIContinuityStatusActivity,
  buildOpenAICompactionEventActivity,
  buildOpenAIAccountNativeActivityRows,
  buildOpenAIProviderToolStatusActivity,
  buildOpenAIProviderToolOutputActivity,
  buildOpenAIWebSocketReconnectActivity,
  registerOpenAIEventBridgeHandlers,
} from '../../src/renderer/components/chat/chat-event-bridge-openai.mjs'
import { collectTurnFileChanges } from '../../src/renderer/components/chat/turn-file-changes.mjs'

function createMemoryLocalStorage() {
  const map = new Map()
  return {
    getItem(key) {
      return map.has(key) ? map.get(key) : null
    },
    setItem(key, value) {
      map.set(String(key), String(value))
    },
    removeItem(key) {
      map.delete(String(key))
    },
    clear() {
      map.clear()
    },
  }
}

test('provider tool output is terminal and preserves local success or failure', () => {
  const succeeded = buildOpenAIProviderToolOutputActivity({
    toolCallId: 'call-success',
    toolName: 'shell',
    output: { success: { exitCode: 0 } },
  })
  const failed = buildOpenAIProviderToolOutputActivity({
    toolCallId: 'call-failure',
    toolName: 'shell',
    output: { failure: { exitCode: 1 } },
  })

  assert.equal(succeeded.type, 'result')
  assert.equal(succeeded.isError, false)
  assert.equal(failed.type, 'result')
  assert.equal(failed.isError, true)
})

test('account model reroute status renders as a concise model event', () => {
  const activity = buildOpenAIProviderToolStatusActivity({
    threadId: 'thread-reroute',
    turnId: 'turn-reroute',
    type: 'completed',
    toolCallId: 'model_reroute:turn-reroute',
    toolName: 'model_reroute',
    model: 'gpt-5.2',
    activityKind: 'openai_account_model_reroute',
    delta: 'gpt-5.3-codex → gpt-5.2 · highRiskCyberActivity',
  })

  assert.equal(activity.label, 'Model rerouted')
  assert.equal(activity.detail, 'gpt-5.3-codex → gpt-5.2 · highRiskCyberActivity')
  assert.equal(activity.model, 'gpt-5.2')
  assert.equal(activity.status, 'completed')
})

test('account warning, hook, approval review, and error statuses use concise activity labels', () => {
  const cases = [
    ['openai_account_config_warning', 'Configuration warning'],
    ['openai_account_hook', 'Hook'],
    ['openai_account_auto_approval_review', 'Automatic approval review'],
    ['openai_account_turn_error', 'Provider error'],
  ]

  for (const [activityKind, expectedLabel] of cases) {
    const activity = buildOpenAIProviderToolStatusActivity({
      threadId: 'thread-status-label',
      turnId: 'turn-status-label',
      type: 'warning',
      toolCallId: `${activityKind}:1`,
      toolName: 'provider_activity',
      activityKind,
      delta: 'status: warning',
    })
    assert.equal(activity.label, expectedLabel)
    assert.equal(activity.detail, 'status: warning')
  }
})

test('image generation provider output renders a compact completion instead of serialized metadata', () => {
  const activity = buildOpenAIProviderToolOutputActivity({
    toolCallId: 'image-generation-1',
    toolName: 'image_generation',
    output: {
      type: 'imageGeneration',
      status: 'completed',
      revisedPrompt: 'A refined architectural hero image.',
      savedPath: 'C:/repo/generated/hero.png',
      resultAvailable: true,
    },
  })

  assert.equal(activity.detail, 'Image generated by OpenAI provider tool.')
  assert.equal(activity.output.resultAvailable, true)
  assert.equal(Object.hasOwn(activity.output, 'result'), false)
})

test('native command output uses the canonical command presentation instead of raw JSON', () => {
  const activity = buildOpenAIProviderToolOutputActivity({
    threadId: 'thread-command',
    turnId: 'turn-command',
    toolCallId: 'command-1',
    toolName: 'command_execution',
    output: {
      type: 'commandExecution',
      command: 'npm run build',
      cwd: 'C:\\workspace',
      status: 'failed',
      aggregatedOutput: '\u001b[31mBuild failed\u001b[0m\nMissing package.',
      exitCode: 1,
      durationMs: 859,
    },
  })

  assert.equal(activity.toolName, 'run_command')
  assert.deepEqual(activity.toolInput, {
    command: 'npm run build',
    cwd: 'C:\\workspace',
  })
  assert.equal(activity.detail, 'Build failed\nMissing package.')
  assert.equal(activity.isError, true)
  assert.equal(activity.exitCode, 1)
  assert.equal(activity.durationMs, 859)
  assert.doesNotMatch(activity.detail, /aggregatedOutput|commandExecution/)
})

test('unknown recoverable account activity remains diagnostic-only', () => {
  const rows = buildOpenAIAccountNativeActivityRows({
    threadId: 'thread-unknown',
    turnId: 'turn-unknown',
    accountProtocol: {
      runtime: { version: '0.124.0' },
      unknownActivities: [
        {
          protocolMethod: 'item/started',
          itemType: 'hookPrompt',
          itemId: 'hook-1',
          lifecycle: 'started',
          supportStatus: 'unknown',
        },
        {
          protocolMethod: 'item/completed',
          itemType: 'hookPrompt',
          itemId: 'hook-1',
          lifecycle: 'completed',
          supportStatus: 'unknown',
        },
      ],
    },
  })

  assert.deepEqual(rows, [])
})

async function withChatStore(testFn) {
  const prevWindow = globalThis.window
  const prevLocalStorage = globalThis.localStorage
  const localStorage = createMemoryLocalStorage()
  let injectedCrypto = false
  if (!globalThis.crypto) {
    globalThis.crypto = { randomUUID: () => `uuid_${Math.random().toString(36).slice(2, 10)}` }
    injectedCrypto = true
  }
  globalThis.window = { localStorage }
  globalThis.localStorage = localStorage

  try {
    const mod = await import(`../../src/renderer/store/useChatStore.js?openai_bridge=${Date.now()}_${Math.random().toString(36).slice(2, 8)}`)
    const store = mod.default
    if (typeof store?.setState === 'function' && typeof store?.getInitialState === 'function') {
      store.setState(store.getInitialState(), true)
    }
    return await testFn({ store })
  } finally {
    globalThis.window = prevWindow
    globalThis.localStorage = prevLocalStorage
    if (injectedCrypto) delete globalThis.crypto
  }
}

test('openai continuity activity formats tracked response metadata for tool timeline', () => {
  const activity = buildOpenAIContinuityStatusActivity({
    threadId: 'thread_a',
    turnId: 'turn_1',
    responseId: 'resp_123',
    serviceTier: 'priority',
    continuityMode: 'local_first_hybrid',
    transportMode: 'responses_websocket_experimental',
    configuredTransportMode: 'responses_auto',
    transportSelectionReason: 'auto_preferred_model',
    accountDelegationBackend: 'openai_native',
    accountCollaborationModeId: 'plan',
    websocketReuseMode: 'thread_socket_reused',
    websocketPooledConnection: true,
    websocketReusedConnection: true,
    websocketReconnectAttempt: 2,
    websocketReconnectMaxAttempts: 6,
    websocketReconnectReason: 'socket_closed_before_terminal',
    websocketRecovered: true,
    websocketBypassReason: 'background_mode_enabled',
    websocketStoredResponseRecoveryAttempted: true,
    websocketRecoveredFromStoredResponse: true,
    compactionStrategy: COMPACTION_MODES.PROVIDER_TRUNCATION,
    candidateCompactionModes: [COMPACTION_MODES.PROVIDER_TRUNCATION, COMPACTION_MODES.LOCAL_SUMMARY],
    serverSideCompactionEnabled: true,
    serverSideCompactionThresholdTokens: 180000,
    lastCompactionId: 'cmp_123',
    hostedToolIds: ['web_search', 'file_search'],
    promptCachingEnabled: true,
    accountNativeActivity: {
      webSearch: {
        itemIds: ['web_1'],
        queries: ['Codex docs'],
      },
      commandExecution: {
        itemIds: ['cmd_1'],
        commands: ['git status'],
      },
    },
  })

  assert.equal(activity.type, 'info')
  assert.equal(activity.threadId, 'thread_a')
  assert.equal(activity.turnId, 'turn_1')
  assert.equal(activity.eventKind, 'openai_continuity_status')
  assert.equal(activity.label, 'OpenAI response tracked: resp_123')
  assert.equal(activity.detail, [
    'mode: local_first_hybrid',
    'transport_mode: responses_websocket_experimental',
    'configured_transport_mode: responses_auto',
    'transport_selection_reason: auto_preferred_model',
    'delegation_backend: openai_native',
    'native_collaboration_mode: plan',
    'websocket_reuse_mode: thread_socket_reused',
    'websocket_pooled_connection: true',
    'websocket_reused_connection: true',
    'websocket_reconnect_attempt: 2',
    'websocket_reconnect_max_attempts: 6',
    'websocket_reconnect_reason: socket_closed_before_terminal',
    'websocket_recovered: true',
    'websocket_bypass_reason: background_mode_enabled',
    'websocket_stored_response_recovery_attempted: true',
    'websocket_recovered_from_stored_response: true',
    'prompt_cache: enabled',
    'compaction_strategy: provider_truncation',
    'compaction mode: provider truncation',
    'server_side_compaction: enabled',
    'server_side_threshold_tokens: 180000',
    'service_tier: priority',
    'native_items: web_search, command_execution',
    'hosted_tools: web_search, file_search',
  ].join('\n'))
})

test('openai continuity activity keeps fallback wording when response metadata is partial', () => {
  const activity = buildOpenAIContinuityStatusActivity({
    threadId: 'thread_b',
    turnId: 'turn_2',
    hostedToolIds: [],
  })

  assert.equal(activity.label, 'OpenAI response metadata received')
  assert.equal(activity.detail, [
    'prompt_cache: disabled',
    'hosted_tools: none',
  ].join('\n'))
})

test('openai continuity activity surfaces manual compaction strategy without threshold when only explicit compaction was used', () => {
  const activity = buildOpenAIContinuityStatusActivity({
    threadId: 'thread_c',
    turnId: 'turn_3',
    compactionStrategy: COMPACTION_MODES.PROVIDER_CHAIN_COMPACTION,
    effectiveCompactionTransport: 'responses_server_compaction',
    candidateCompactionModes: [COMPACTION_MODES.PROVIDER_CHAIN_COMPACTION, COMPACTION_MODES.LOCAL_SUMMARY],
    serverSideCompactionEnabled: false,
    hostedToolIds: [],
    promptCachingEnabled: true,
  })

  assert.equal(activity.detail, [
    'prompt_cache: enabled',
    'compaction_strategy: provider_chain_compaction',
    'effective_compaction_transport: responses_server_compaction',
    'compaction mode: provider chain compaction',
    'server_side_compaction: disabled',
    'hosted_tools: none',
  ].join('\n'))
})

test('openai continuity activity keeps automatic compaction in diagnostics without surfacing a milestone card', () => {
  const activity = buildOpenAIContinuityStatusActivity({
    threadId: 'thread_auto',
    turnId: 'turn_auto',
    responseId: 'resp_auto_1',
    compactionStrategy: COMPACTION_MODES.PROVIDER_TRUNCATION,
    serverSideCompactionEnabled: true,
    serverSideCompactionThresholdTokens: 180000,
    autoCompactionApplied: true,
    autoCompactionIds: ['cmp_auto_1'],
    compactionEventType: 'provider_truncation',
    compactionEventPhase: 'applied',
    compactionEventOccurred: true,
    canonicalHandoffUsed: true,
    carryForwardSource: 'both',
    promptCachingEnabled: true,
    hostedToolIds: [],
  })

  assert.equal(activity.compactionMilestone, undefined)
  assert.equal(activity.compactionMilestoneTitle, undefined)
  assert.equal(activity.compactionMilestoneDetail, undefined)
  assert.match(String(activity.detail || ''), /boundary: compaction applied \(provider truncation\)/)
  assert.match(String(activity.detail || ''), /canonical handoff: used/)
  assert.match(String(activity.detail || ''), /carry-forward source: continuity packet \+ compaction handoff/)
})

test('openai compaction event activity marks successful manual compaction as a stream milestone', () => {
  const activity = buildOpenAICompactionEventActivity({
    threadId: 'thread_compact',
    turnId: 'turn_compact',
    providerId: 'openai',
    model: 'gpt-5.4',
    status: 'applied',
    mode: 'manual',
    reason: 'compacted',
    selectedCompactionMode: COMPACTION_MODES.PROVIDER_CHAIN_COMPACTION,
    candidateCompactionModes: [COMPACTION_MODES.PROVIDER_CHAIN_COMPACTION, COMPACTION_MODES.LOCAL_SUMMARY],
    responseId: 'resp_compact',
    compactionId: 'cmp_compact',
    accountBridgeThreadId: 'bridge_compact',
    accountBridgeTurnId: 'bridge_turn_compact',
    contextCompactionGeneration: 2,
  })

  assert.equal(activity.eventKind, 'openai_compaction_event')
  assert.match(String(activity.detail || ''), /compaction mode: provider chain compaction/)
  assert.equal(activity.compactionMilestone, true)
  assert.equal(activity.compactionMilestoneTitle, 'Context compacted before the next turn')
  assert.match(String(activity.compactionMilestoneDetail || ''), /OpenAI manual server-side compaction/)
  assert.equal(activity.accountBridgeThreadId, 'bridge_compact')
  assert.equal(activity.accountBridgeTurnId, 'bridge_turn_compact')
  assert.equal(activity.contextCompactionGeneration, 2)
})

test('openai compaction event activity renders requested compaction as a coalescing live row', () => {
  const activity = buildOpenAICompactionEventActivity({
    activityId: 'openai_compaction:thread_compact:turn_compact:automatic:provider_chain_compaction',
    threadId: 'thread_compact',
    turnId: 'turn_compact',
    providerId: 'openai',
    model: 'gpt-5.4',
    status: 'requested',
    mode: 'automatic',
    reason: 'automatic_compaction_requested',
    selectedCompactionMode: COMPACTION_MODES.PROVIDER_CHAIN_COMPACTION,
    candidateCompactionModes: [COMPACTION_MODES.PROVIDER_CHAIN_COMPACTION, COMPACTION_MODES.LOCAL_SUMMARY],
    compactionEventType: 'provider_chain_compaction',
    compactionEventPhase: 'running',
    compactionEventOccurred: false,
  })

  assert.equal(activity.id, 'openai_compaction:thread_compact:turn_compact:automatic:provider_chain_compaction')
  assert.equal(activity.coalesce, true)
  assert.equal(activity.type, 'info')
  assert.equal(activity.label, 'Compacting context')
  assert.equal(activity.compactionMilestone, false)
})

test('openai compaction event activity renders running compaction distinctly from the request', () => {
  const activity = buildOpenAICompactionEventActivity({
    activityId: 'openai_compaction:thread_compact:turn_compact:automatic:provider_chain_compaction',
    threadId: 'thread_compact',
    turnId: 'turn_compact',
    providerId: 'openai',
    model: 'gpt-5.4',
    status: 'running',
    mode: 'automatic',
    reason: 'automatic_compaction_requested',
    selectedCompactionMode: COMPACTION_MODES.PROVIDER_CHAIN_COMPACTION,
    candidateCompactionModes: [COMPACTION_MODES.PROVIDER_CHAIN_COMPACTION, COMPACTION_MODES.LOCAL_SUMMARY],
    compactionEventType: 'provider_chain_compaction',
    compactionEventPhase: 'running',
    compactionEventOccurred: false,
  })

  assert.equal(activity.coalesce, true)
  assert.equal(activity.type, 'info')
  assert.equal(activity.label, 'Compacting context')
  assert.equal(activity.compactionMilestone, false)
})

test('openai compaction event activity uses Codex account wording for account-native compaction', () => {
  const activity = buildOpenAICompactionEventActivity({
    threadId: 'thread_account_compact',
    turnId: 'turn_account_compact',
    providerId: 'openai',
    model: 'gpt-5.4',
    status: 'applied',
    mode: 'manual',
    reason: 'compacted',
    selectedCompactionMode: COMPACTION_MODES.CODEX_THREAD_COMPACTION,
    candidateCompactionModes: [COMPACTION_MODES.CODEX_THREAD_COMPACTION, COMPACTION_MODES.LOCAL_SUMMARY],
    compactionEventType: 'codex_thread_compaction',
    compactionId: 'cmp_account_compact',
  })

  assert.match(String(activity.detail || ''), /compaction mode: codex thread compaction/)
  assert.match(String(activity.compactionMilestoneDetail || ''), /Codex account thread compaction/)
})

test('openai websocket reconnect activity formats retry and fallback states for the timeline', () => {
  const reconnecting = buildOpenAIWebSocketReconnectActivity({
    threadId: 'thread_ws',
    turnId: 'turn_ws',
    status: 'reconnecting',
    attempt: 2,
    maxAttempts: 6,
    reason: 'socket_closed_before_terminal',
    waitMs: 5000,
  })
  const fallback = buildOpenAIWebSocketReconnectActivity({
    threadId: 'thread_ws',
    turnId: 'turn_ws',
    status: 'fallback',
    attempt: 6,
    maxAttempts: 6,
    reason: 'socket_closed_before_terminal',
  })
  const recoveringStoredResponse = buildOpenAIWebSocketReconnectActivity({
    threadId: 'thread_ws',
    turnId: 'turn_ws',
    status: 'recovering_stored_response',
    reason: 'socket_closed_after_partial_output',
    responseId: 'resp_ws_partial_1',
  })

  assert.equal(reconnecting.label, 'Reconnecting... 2/6')
  assert.match(String(reconnecting.detail || ''), /wait_ms: 5000/)
  assert.equal(fallback.type, 'warning')
  assert.equal(fallback.label, 'Falling back to the standard OpenAI stream')
  assert.equal(recoveringStoredResponse.label, 'Recovering the final response from stored state')
  assert.match(String(recoveringStoredResponse.detail || ''), /response_id: resp_ws_partial_1/)
})

test('openai event bridge registration wires subscriptions and unsubscribes on cleanup', () => {
  const handlers = new Map()
  const unsubscribed = []
  const activities = []
  const processingModes = []

  const events = {
    onSourceUrl: Symbol('onSourceUrl'),
    onSourceDocument: Symbol('onSourceDocument'),
    onProviderToolStatus: Symbol('onProviderToolStatus'),
    onProviderToolOutput: Symbol('onProviderToolOutput'),
    onOpenAIContinuityStatus: Symbol('onOpenAIContinuityStatus'),
    onOpenAICompactionEvent: Symbol('onOpenAICompactionEvent'),
    onOpenAIWebSocketReconnect: Symbol('onOpenAIWebSocketReconnect'),
    onBackgroundResponseQueued: Symbol('onBackgroundResponseQueued'),
    onBackgroundResponseCompleted: Symbol('onBackgroundResponseCompleted'),
    onBackgroundResponseFailed: Symbol('onBackgroundResponseFailed'),
  }

  const useChatStore = {
    getState: () => ({
      pushToolActivity: (activity) => activities.push(activity),
      recordReturnedProcessingMode: (mode, options) => processingModes.push({ mode, options }),
      setPlanActionBusy: () => {},
      markBackgroundPending: () => {},
      finalizeReasoning: () => {},
      markReasoningDone: () => {},
      finalizeMessage: () => {},
      markError: () => {},
    }),
  }

  const cleanup = registerOpenAIEventBridgeHandlers({
    safeSub: (eventKey, handler, name) => {
      handlers.set(name, handler)
      return () => unsubscribed.push(name)
    },
    chatApi: events,
    useChatStore,
    setReasoningMetaForMessage: () => {},
  })

  assert.equal(typeof handlers.get('onSourceUrl'), 'function')
  assert.equal(typeof handlers.get('onBackgroundResponseCompleted'), 'function')

  handlers.get('onSourceUrl')({ threadId: 'thread-1', url: 'https://example.com' })
  handlers.get('onOpenAIContinuityStatus')({
    threadId: 'thread-1',
    responseId: 'resp_123',
    serviceTier: 'priority',
  })
  handlers.get('onOpenAICompactionEvent')({ threadId: 'thread-1', status: 'applied', mode: 'manual' })
  handlers.get('onOpenAIWebSocketReconnect')({ threadId: 'thread-1', status: 'reconnecting', attempt: 1, maxAttempts: 6 })

  assert.equal(activities.length, 4)
  assert.equal(activities[0].eventKind, 'source_url')
  assert.equal(activities[1].eventKind, 'openai_continuity_status')
  assert.equal(activities[2].eventKind, 'openai_compaction_event')
  assert.equal(activities[3].eventKind, 'openai_websocket_reconnect')
  assert.deepEqual(processingModes, [{
    mode: 'priority',
    options: { threadId: 'thread-1', providerId: 'openai' },
  }])

  cleanup()
  assert.deepEqual(unsubscribed.sort(), [
    'onBackgroundResponseCompleted',
    'onBackgroundResponseFailed',
    'onBackgroundResponseQueued',
    'onOpenAICompactionEvent',
    'onOpenAIContinuityStatus',
    'onOpenAIWebSocketReconnect',
    'onProviderToolOutput',
    'onProviderToolStatus',
    'onSourceDocument',
    'onSourceUrl',
  ])
})

test('openai compaction lifecycle coalesces onto one live execution activity id', async () => {
  await withChatStore(async ({ store }) => {
    const activityId = 'openai_compaction:thread-live:turn-live:automatic:provider_chain_compaction'
    const state = store.getState()
    state.setActiveThread('thread-live')

    state.pushToolActivity(buildOpenAICompactionEventActivity({
      activityId,
      threadId: 'thread-live',
      turnId: 'turn-live',
      providerId: 'openai',
      model: 'gpt-5.4',
      status: 'requested',
      mode: 'automatic',
      reason: 'automatic_compaction_requested',
      selectedCompactionMode: COMPACTION_MODES.PROVIDER_CHAIN_COMPACTION,
      candidateCompactionModes: [COMPACTION_MODES.PROVIDER_CHAIN_COMPACTION, COMPACTION_MODES.LOCAL_SUMMARY],
      compactionEventType: 'provider_chain_compaction',
      compactionEventPhase: 'running',
      compactionEventOccurred: false,
    }))
    state.pushToolActivity(buildOpenAICompactionEventActivity({
      activityId,
      threadId: 'thread-live',
      turnId: 'turn-live',
      providerId: 'openai',
      model: 'gpt-5.4',
      status: 'applied',
      mode: 'automatic',
      reason: 'compacted',
      selectedCompactionMode: COMPACTION_MODES.PROVIDER_CHAIN_COMPACTION,
      candidateCompactionModes: [COMPACTION_MODES.PROVIDER_CHAIN_COMPACTION, COMPACTION_MODES.LOCAL_SUMMARY],
      compactionEventType: 'provider_chain_compaction',
      compactionEventPhase: 'resumed_after',
      compactionEventOccurred: true,
      compactionId: 'cmp_live_1',
    }))

    const turn = store.getState().liveExecution.turnsById['turn-live']
    assert.ok(turn)
    assert.deepEqual(turn.eventOrder, [`activity:${activityId}`])
    const event = turn.eventsById[`activity:${activityId}`]
    assert.ok(event)
    assert.equal(event.status, 'done')
    assert.equal(String(event?.activity?.compactionMilestoneTitle || ''), 'Context compacted before the next turn')
  })
})

test('openai continuity status emits native Codex account activity summaries into the tool timeline', () => {
  const handlers = new Map()
  const activities = []

  const useChatStore = {
    getState: () => ({
      pushToolActivity: (activity) => activities.push(activity),
      setPlanActionBusy: () => {},
      markBackgroundPending: () => {},
      finalizeReasoning: () => {},
      markReasoningDone: () => {},
      finalizeMessage: () => {},
      markError: () => {},
    }),
  }

  registerOpenAIEventBridgeHandlers({
    safeSub: (_eventKey, handler, name) => {
      handlers.set(name, handler)
      return () => {}
    },
    chatApi: {
      onSourceUrl: Symbol('onSourceUrl'),
      onSourceDocument: Symbol('onSourceDocument'),
      onProviderToolStatus: Symbol('onProviderToolStatus'),
      onProviderToolOutput: Symbol('onProviderToolOutput'),
      onOpenAIContinuityStatus: Symbol('onOpenAIContinuityStatus'),
      onOpenAICompactionEvent: Symbol('onOpenAICompactionEvent'),
      onOpenAIWebSocketReconnect: Symbol('onOpenAIWebSocketReconnect'),
      onBackgroundResponseQueued: Symbol('onBackgroundResponseQueued'),
      onBackgroundResponseCompleted: Symbol('onBackgroundResponseCompleted'),
      onBackgroundResponseFailed: Symbol('onBackgroundResponseFailed'),
    },
    useChatStore,
    setReasoningMetaForMessage: () => {},
  })

  handlers.get('onOpenAIContinuityStatus')({
    threadId: 'thread-native-summaries',
    turnId: 'turn-native-summaries',
    authMethod: 'account',
    responseId: 'resp_native_1',
    accountNativeActivity: {
      webSearch: {
        itemIds: ['web_native_1'],
        queries: ['Codex app-server items'],
        actionTypes: ['search'],
      },
      commandExecution: {
        itemIds: ['cmd_native_1'],
        commands: ['git status'],
        cwds: ['C:/repo'],
        statuses: ['completed'],
        aggregatedOutput: 'On branch main',
      },
      fileChange: {
        itemIds: ['file_native_1'],
        changes: [
          {
            path: 'public/index.html',
            kind: 'modify',
            diff: [
              '@@ -1,2 +1,3 @@',
              ' <main>',
              '-  <h1>Old</h1>',
              '+  <h1>New</h1>',
              '+  <p>Fresh</p>',
            ].join('\n'),
          },
          {
            path: 'public/styles.css',
            kind: 'create',
            addedLines: 8,
            removedLines: 0,
          },
        ],
        paths: ['public/index.html', 'public/styles.css'],
        changeKinds: ['modify', 'create'],
        statuses: ['completed'],
        outputPreview: 'apply_patch succeeded',
      },
      imageGeneration: {
        itemIds: ['image_generation_native_1'],
        statuses: ['completed'],
        revisedPrompts: ['A refined architectural hero image.'],
        savedPaths: ['C:/repo/generated/hero.png'],
        resultAvailable: true,
      },
      plan: {
        itemIds: ['plan_native_1'],
        text: 'Inspect then implement',
        statuses: ['completed'],
      },
      reviewMode: {
        itemIds: ['review_native_1'],
        reviewIds: ['review_session_1'],
        itemTypes: ['enteredReviewMode'],
        entered: true,
        exited: false,
      },
    },
  })

  assert.equal(activities.length, 7)
  assert.equal(activities[0].eventKind, 'openai_continuity_status')
  assert.equal(activities[1].eventKind, 'openai_account_native_web_search')
  assert.match(String(activities[1].detail || ''), /queries: Codex app-server items/)
  assert.equal(activities[2].eventKind, 'openai_account_native_command_execution')
  assert.match(String(activities[2].detail || ''), /output: On branch main/)
  assert.equal(activities[3].eventKind, 'openai_account_native_file_change')
  assert.equal(Array.isArray(activities[3].fileChanges), true)
  assert.equal(activities[3].fileChanges.length, 2)
  assert.equal(activities[3].fileChange.filePath, 'public/index.html')
  assert.equal(activities[3].fileChange.addedLines, 2)
  assert.equal(activities[3].fileChange.removedLines, 1)
  assert.match(String(activities[3].fileChange.diffText || ''), /<h1>New<\/h1>/)
  assert.equal(activities[4].eventKind, 'openai_account_native_image_generation')
  assert.equal(activities[4].toolName, 'image_generation')
  assert.match(String(activities[4].detail || ''), /saved_path: C:\/repo\/generated\/hero\.png/)
  assert.match(String(activities[4].detail || ''), /result_available: true/)
  assert.equal(activities[5].eventKind, 'openai_account_native_plan')
  assert.match(String(activities[5].detail || ''), /text: Inspect then implement/)
  assert.equal(activities[6].eventKind, 'openai_account_native_review_mode')
  assert.match(String(activities[6].detail || ''), /entered: true/)
})

test('openai provider file-change outputs become collectible file rows for live turns', () => {
  const handlers = new Map()
  const activities = []

  const useChatStore = {
    getState: () => ({
      pushToolActivity: (activity) => activities.push(activity),
      setPlanActionBusy: () => {},
      markBackgroundPending: () => {},
      finalizeReasoning: () => {},
      markReasoningDone: () => {},
      finalizeMessage: () => {},
      markError: () => {},
    }),
  }

  registerOpenAIEventBridgeHandlers({
    safeSub: (_eventKey, handler, name) => {
      handlers.set(name, handler)
      return () => {}
    },
    chatApi: {
      onSourceUrl: Symbol('onSourceUrl'),
      onSourceDocument: Symbol('onSourceDocument'),
      onProviderToolStatus: Symbol('onProviderToolStatus'),
      onProviderToolOutput: Symbol('onProviderToolOutput'),
      onOpenAIContinuityStatus: Symbol('onOpenAIContinuityStatus'),
      onOpenAICompactionEvent: Symbol('onOpenAICompactionEvent'),
      onOpenAIWebSocketReconnect: Symbol('onOpenAIWebSocketReconnect'),
      onBackgroundResponseQueued: Symbol('onBackgroundResponseQueued'),
      onBackgroundResponseCompleted: Symbol('onBackgroundResponseCompleted'),
      onBackgroundResponseFailed: Symbol('onBackgroundResponseFailed'),
    },
    useChatStore,
    setReasoningMetaForMessage: () => {},
  })

  handlers.get('onProviderToolOutput')({
    threadId: 'thread-live-provider-files',
    turnId: 'turn-live-provider-files',
    toolName: 'file_change',
    output: {
      changes: [
        {
          path: 'public/index.html',
          kind: 'modify',
          diff: '@@ -1,2 +1,3 @@\n <main>\n-  <h1>Old</h1>\n+  <h1>New</h1>\n+  <p>Fresh</p>',
        },
        { path: 'public/styles.css', kind: 'create', addedLines: 44, removedLines: 0 },
      ],
    },
  })

  assert.equal(activities.length, 1)
  assert.equal(activities[0].eventKind, 'provider_tool_output')
  assert.equal(Array.isArray(activities[0].fileChanges), true)
  assert.equal(activities[0].fileChanges.length, 2)
  assert.match(String(activities[0].fileChanges[0].diffText || ''), /<h1>New<\/h1>/)

  const rows = collectTurnFileChanges(activities)
  assert.deepEqual(
    rows.map((row) => ({
      filePath: row.fileChange.filePath,
      changeType: row.fileChange.changeType,
      addedLines: row.fileChange.addedLines,
      removedLines: row.fileChange.removedLines,
    })),
    [
      {
        filePath: 'public/index.html',
        changeType: 'modified',
        addedLines: 2,
        removedLines: 1,
      },
      {
        filePath: 'public/styles.css',
        changeType: 'created',
        addedLines: 44,
        removedLines: 0,
      },
    ],
  )
  assert.match(String(rows[0]?.fileChange?.diffText || ''), /<h1>New<\/h1>/)
})

test('openai background handlers update the payload thread (active or inactive)', () => {
  const handlers = new Map()
  const calls = []

  const useChatStore = {
    getState: () => ({
      pushToolActivity: () => {},
      setPlanActionBusy: (busy) => calls.push(['setPlanActionBusy', busy]),
      markBackgroundPending: (messageId, note) => calls.push(['markBackgroundPending', messageId, note]),
      finalizeReasoning: (messageId, text) => calls.push(['finalizeReasoning', messageId, text]),
      markReasoningDone: (messageId) => calls.push(['markReasoningDone', messageId]),
      finalizeMessage: (messageId, text) => calls.push(['finalizeMessage', messageId, text]),
      markError: (messageId, text) => calls.push(['markError', messageId, text]),
    }),
  }

  registerOpenAIEventBridgeHandlers({
    safeSub: (eventKey, handler, name) => {
      handlers.set(name, handler)
      return () => {}
    },
    chatApi: {
      onSourceUrl: Symbol('onSourceUrl'),
      onSourceDocument: Symbol('onSourceDocument'),
      onProviderToolStatus: Symbol('onProviderToolStatus'),
      onProviderToolOutput: Symbol('onProviderToolOutput'),
      onOpenAIContinuityStatus: Symbol('onOpenAIContinuityStatus'),
      onOpenAICompactionEvent: Symbol('onOpenAICompactionEvent'),
      onOpenAIWebSocketReconnect: Symbol('onOpenAIWebSocketReconnect'),
      onBackgroundResponseQueued: Symbol('onBackgroundResponseQueued'),
      onBackgroundResponseCompleted: Symbol('onBackgroundResponseCompleted'),
      onBackgroundResponseFailed: Symbol('onBackgroundResponseFailed'),
    },
    useChatStore,
    setReasoningMetaForMessage: (messageId, patch, threadId) => calls.push(['setReasoningMetaForMessage', messageId, patch.mode, threadId]),
  })

  handlers.get('onBackgroundResponseQueued')({
    threadId: 'thread-inactive',
    messageId: 'msg_1',
    note: 'queued',
  })
  handlers.get('onBackgroundResponseCompleted')({
    threadId: 'thread-active',
    messageId: 'msg_2',
    full: 'Done',
    reasoning: 'Summary',
  })
  handlers.get('onBackgroundResponseFailed')({
    threadId: 'thread-inactive',
    messageId: 'msg_3',
    message: 'boom',
  })

  assert.equal(calls.some(([name]) => name === 'markBackgroundPending'), true)
  assert.equal(calls.some(([name]) => name === 'markError'), true)
  assert.equal(calls.some(([name]) => name === 'finalizeMessage'), true)
  assert.equal(calls.some(([name]) => name === 'setReasoningMetaForMessage'), true)
})

test('openai background completion lands reasoning in the settled execution stream for the queued turn', async () => {
  await withChatStore(async ({ store }) => {
    const handlers = new Map()
    const api = store.getState()
    api.setActiveThread('thread-bg-handler')
    const messageId = api.addAssistantPlaceholder({ threadId: 'thread-bg-handler' })

    registerOpenAIEventBridgeHandlers({
      safeSub: (_eventKey, handler, name) => {
        handlers.set(name, handler)
        return () => {}
      },
      chatApi: {
        onSourceUrl: Symbol('onSourceUrl'),
        onSourceDocument: Symbol('onSourceDocument'),
        onProviderToolStatus: Symbol('onProviderToolStatus'),
        onProviderToolOutput: Symbol('onProviderToolOutput'),
        onOpenAIContinuityStatus: Symbol('onOpenAIContinuityStatus'),
        onOpenAICompactionEvent: Symbol('onOpenAICompactionEvent'),
        onOpenAIWebSocketReconnect: Symbol('onOpenAIWebSocketReconnect'),
        onBackgroundResponseQueued: Symbol('onBackgroundResponseQueued'),
        onBackgroundResponseCompleted: Symbol('onBackgroundResponseCompleted'),
        onBackgroundResponseFailed: Symbol('onBackgroundResponseFailed'),
      },
      useChatStore: store,
      setReasoningMetaForMessage: (targetMessageId, patch, threadId) => {
        store.getState().setReasoningMeta(targetMessageId, patch, threadId ? { threadId } : undefined)
      },
    })

    handlers.get('onBackgroundResponseQueued')({
      threadId: 'thread-bg-handler',
      turnId: 'turn-bg-handler',
      messageId,
      note: 'queued',
      queuedAt: 1_000,
      jobId: 'job-bg-handler',
      responseId: 'resp-bg-handler',
    })

    handlers.get('onBackgroundResponseCompleted')({
      threadId: 'thread-bg-handler',
      turnId: 'turn-bg-handler',
      messageId,
      full: 'Background answer.',
      reasoning: 'Background reasoning persisted.',
      reasoningTokens: 3,
      phase: 'answer',
      finalDocument: {
        schemaVersion: 1,
        threadId: 'thread-bg-handler',
        turnId: 'turn-bg-handler',
        messageId,
        ownership: 'final-document',
        text: 'Background answer.',
        parts: [{
          threadId: 'thread-bg-handler',
          turnId: 'turn-bg-handler',
          messageId,
          partId: `${messageId}:final-document:1`,
          appendOrder: 1,
          sequence: 1,
          status: 'completed',
          ownership: 'final-document',
          kind: 'markdown',
          text: 'Background answer.',
        }],
      },
    })

    const message = store.getState().messages.find((entry) => entry.id === messageId)
    assert.ok(message)
    assert.equal(String(message?.content || ''), 'Background answer.')
    assert.equal(String(message?.reasoning || ''), 'Background reasoning persisted.')
    assert.equal(message?.reasoningDone, true)
    assert.equal(String(message?.streamMeta?.turnId || ''), 'turn-bg-handler')
    assert.deepEqual(message?.finalDocument?.parts?.map((part) => part.partId), [`${messageId}:final-document:1`])
    assert.equal(message?.finalDocument?.text, 'Background answer.')

    const turn = store.getState().liveExecution.turnsById['turn-bg-handler']
    assert.ok(turn)
    const reasoningEvents = turn.eventOrder
      .map((eventId) => turn.eventsById[eventId])
      .filter((event) => event?.kind === 'reasoning' && event?.archived !== true)
    assert.equal(reasoningEvents.length, 1)
    assert.equal(String(reasoningEvents[0]?.detail || ''), 'Background reasoning persisted.')
    assert.equal(String(reasoningEvents[0]?.status || ''), 'done')
  })
})

test('openai continuity status patches auth and transport metadata onto the active assistant turn', async () => {
  await withChatStore(async ({ store }) => {
    const handlers = new Map()
    const api = store.getState()
    api.setActiveThread('thread-openai-meta')
    const messageId = api.addAssistantPlaceholder({ threadId: 'thread-openai-meta' })
    api.markStreamStarted(messageId, {
      threadId: 'thread-openai-meta',
      turnId: 'turn-openai-meta',
      startedAt: 2_000,
      providerId: 'openai',
      model: 'gpt-5.4',
    })

    registerOpenAIEventBridgeHandlers({
      safeSub: (_eventKey, handler, name) => {
        handlers.set(name, handler)
        return () => {}
      },
      chatApi: {
        onSourceUrl: Symbol('onSourceUrl'),
        onSourceDocument: Symbol('onSourceDocument'),
        onProviderToolStatus: Symbol('onProviderToolStatus'),
        onProviderToolOutput: Symbol('onProviderToolOutput'),
        onOpenAIContinuityStatus: Symbol('onOpenAIContinuityStatus'),
        onOpenAICompactionEvent: Symbol('onOpenAICompactionEvent'),
        onOpenAIWebSocketReconnect: Symbol('onOpenAIWebSocketReconnect'),
        onBackgroundResponseQueued: Symbol('onBackgroundResponseQueued'),
        onBackgroundResponseCompleted: Symbol('onBackgroundResponseCompleted'),
        onBackgroundResponseFailed: Symbol('onBackgroundResponseFailed'),
      },
      useChatStore: store,
      setReasoningMetaForMessage: (targetMessageId, patch, threadId) => {
        store.getState().setReasoningMeta(targetMessageId, patch, threadId ? { threadId } : undefined)
      },
    })

    handlers.get('onOpenAIContinuityStatus')({
      threadId: 'thread-openai-meta',
      turnId: 'turn-openai-meta',
      providerId: 'openai',
      model: 'gpt-5.4',
      authMethod: 'account',
      transportMode: 'codex_app_server_chatgpt',
      responseId: 'resp_openai_meta',
    })

    const message = store.getState().messages.find((entry) => entry.id === messageId)
    assert.ok(message)
    assert.equal(String(message?.streamMeta?.authMethod || ''), 'account')
    assert.equal(String(message?.streamMeta?.transportMode || ''), 'codex_app_server_chatgpt')
    assert.equal(String(message?.streamMeta?.providerId || ''), 'openai')
    assert.equal(String(message?.streamMeta?.model || ''), 'gpt-5.4')
  })
})

test('assistant commentary lands as a live execution-stream reasoning event for the active turn', async () => {
  await withChatStore(async ({ store }) => {
    const handlers = new Map()
    const api = store.getState()
    api.setActiveThread('thread-commentary-live')
    const messageId = api.addAssistantPlaceholder({ threadId: 'thread-commentary-live' })
    api.markStreamStarted(messageId, {
      threadId: 'thread-commentary-live',
      turnId: 'turn-commentary-live',
      startedAt: 1_000,
    })

    registerOpenAIEventBridgeHandlers({
      safeSub: (_eventKey, handler, name) => {
        handlers.set(name, handler)
        return () => {}
      },
      chatApi: {
        onSourceUrl: Symbol('onSourceUrl'),
        onSourceDocument: Symbol('onSourceDocument'),
        onProviderToolStatus: Symbol('onProviderToolStatus'),
        onProviderToolOutput: Symbol('onProviderToolOutput'),
        onOpenAIContinuityStatus: Symbol('onOpenAIContinuityStatus'),
        onOpenAICompactionEvent: Symbol('onOpenAICompactionEvent'),
        onOpenAIWebSocketReconnect: Symbol('onOpenAIWebSocketReconnect'),
        onBackgroundResponseQueued: Symbol('onBackgroundResponseQueued'),
        onBackgroundResponseCompleted: Symbol('onBackgroundResponseCompleted'),
        onBackgroundResponseFailed: Symbol('onBackgroundResponseFailed'),
      },
      useChatStore: store,
      setReasoningMetaForMessage: (targetMessageId, patch, threadId) => {
        store.getState().setReasoningMeta(targetMessageId, patch, threadId ? { threadId } : undefined)
      },
    })

    const state = store.getState()
    state.pushToolActivity({
      id: 'assistant_commentary:turn-commentary-live:1',
      type: 'reasoning',
      eventKind: 'assistant_commentary',
      threadId: 'thread-commentary-live',
      turnId: 'turn-commentary-live',
      label: 'Assistant update',
      detail: 'I will inspect the workspace first.',
      round: 1,
      createdAt: 1_010,
      coalesce: true,
    })

    const turn = store.getState().liveExecution.turnsById['turn-commentary-live']
    assert.ok(turn)
    const reasoningEvents = turn.eventOrder
      .map((eventId) => turn.eventsById[eventId])
      .filter((event) => event?.kind === 'reasoning' && event?.archived !== true)
    assert.equal(reasoningEvents.length, 1)
    assert.equal(String(reasoningEvents[0]?.detail || ''), 'I will inspect the workspace first.')
    assert.equal(String(reasoningEvents[0]?.status || ''), 'done')
  })
})

test('openai provider tool input emits one summary activity and keeps deltas local-only', () => {
  const handlers = new Map()
  const activities = []

  const useChatStore = {
    getState: () => ({
      pushToolActivity: (activity) => activities.push(activity),
      setPlanActionBusy: () => {},
      markBackgroundPending: () => {},
      finalizeReasoning: () => {},
      markReasoningDone: () => {},
      finalizeMessage: () => {},
      markError: () => {},
    }),
  }

  registerOpenAIEventBridgeHandlers({
    safeSub: (_eventKey, handler, name) => {
      handlers.set(name, handler)
      return () => {}
    },
    chatApi: {
      onSourceUrl: Symbol('onSourceUrl'),
      onSourceDocument: Symbol('onSourceDocument'),
      onProviderToolStatus: Symbol('onProviderToolStatus'),
      onProviderToolOutput: Symbol('onProviderToolOutput'),
      onOpenAIContinuityStatus: Symbol('onOpenAIContinuityStatus'),
      onOpenAICompactionEvent: Symbol('onOpenAICompactionEvent'),
      onOpenAIWebSocketReconnect: Symbol('onOpenAIWebSocketReconnect'),
      onBackgroundResponseQueued: Symbol('onBackgroundResponseQueued'),
      onBackgroundResponseCompleted: Symbol('onBackgroundResponseCompleted'),
      onBackgroundResponseFailed: Symbol('onBackgroundResponseFailed'),
    },
    useChatStore,
    setReasoningMetaForMessage: () => {},
  })

  handlers.get('onProviderToolStatus')({
    type: 'tool-input-start',
    turnId: 'turn-1',
    toolCallId: 'call-1',
    toolName: 'tool',
  })
  handlers.get('onProviderToolStatus')({
    type: 'tool-input-delta',
    turnId: 'turn-1',
    toolCallId: 'call-1',
    toolName: 'tool',
    delta: '{"path":',
  })
  handlers.get('onProviderToolStatus')({
    type: 'tool-input-delta',
    turnId: 'turn-1',
    toolCallId: 'call-1',
    toolName: 'tool',
    delta: '"todo_app.py"}',
  })

  assert.equal(activities.length, 1)
  assert.equal(activities.every((activity) => activity.coalesce === true), true)
  assert.equal(activities.every((activity) => activity.id === 'provider_tool:turn-1:call-1'), true)
  assert.equal(activities[0].stepId, 'call-1')
  assert.equal(activities[0].detail, 'Collecting provider tool input...')
})

test('openai provider tool input synthesizes one summary activity when deltas arrive before start', () => {
  const handlers = new Map()
  const activities = []

  const useChatStore = {
    getState: () => ({
      pushToolActivity: (activity) => activities.push(activity),
      setPlanActionBusy: () => {},
      markBackgroundPending: () => {},
      finalizeReasoning: () => {},
      markReasoningDone: () => {},
      finalizeMessage: () => {},
      markError: () => {},
    }),
  }

  registerOpenAIEventBridgeHandlers({
    safeSub: (_eventKey, handler, name) => {
      handlers.set(name, handler)
      return () => {}
    },
    chatApi: {
      onSourceUrl: Symbol('onSourceUrl'),
      onSourceDocument: Symbol('onSourceDocument'),
      onProviderToolStatus: Symbol('onProviderToolStatus'),
      onProviderToolOutput: Symbol('onProviderToolOutput'),
      onOpenAIContinuityStatus: Symbol('onOpenAIContinuityStatus'),
      onOpenAICompactionEvent: Symbol('onOpenAICompactionEvent'),
      onOpenAIWebSocketReconnect: Symbol('onOpenAIWebSocketReconnect'),
      onBackgroundResponseQueued: Symbol('onBackgroundResponseQueued'),
      onBackgroundResponseCompleted: Symbol('onBackgroundResponseCompleted'),
      onBackgroundResponseFailed: Symbol('onBackgroundResponseFailed'),
    },
    useChatStore,
    setReasoningMetaForMessage: () => {},
  })

  handlers.get('onProviderToolStatus')({
    type: 'tool-input-delta',
    turnId: 'turn-2',
    toolCallId: 'call-2',
    toolName: 'tool',
    delta: '{"path":"one"}',
  })
  handlers.get('onProviderToolStatus')({
    type: 'tool-input-delta',
    turnId: 'turn-2',
    toolCallId: 'call-2',
    toolName: 'tool',
    delta: '{"path":"two"}',
  })

  assert.equal(activities.length, 1)
  assert.equal(activities[0].id, 'provider_tool:turn-2:call-2')
  assert.equal(activities[0].stepId, 'call-2')
  assert.equal(activities[0].detail, 'Collecting provider tool input...')
})

test('openai provider tool input summary forwards toolInput and shares output session id family', () => {
  const handlers = new Map()
  const activities = []

  const useChatStore = {
    getState: () => ({
      pushToolActivity: (activity) => activities.push(activity),
      setPlanActionBusy: () => {},
      markBackgroundPending: () => {},
      finalizeReasoning: () => {},
      markReasoningDone: () => {},
      finalizeMessage: () => {},
      markError: () => {},
    }),
  }

  registerOpenAIEventBridgeHandlers({
    safeSub: (_eventKey, handler, name) => {
      handlers.set(name, handler)
      return () => {}
    },
    chatApi: {
      onSourceUrl: Symbol('onSourceUrl'),
      onSourceDocument: Symbol('onSourceDocument'),
      onProviderToolStatus: Symbol('onProviderToolStatus'),
      onProviderToolOutput: Symbol('onProviderToolOutput'),
      onOpenAIContinuityStatus: Symbol('onOpenAIContinuityStatus'),
      onOpenAICompactionEvent: Symbol('onOpenAICompactionEvent'),
      onOpenAIWebSocketReconnect: Symbol('onOpenAIWebSocketReconnect'),
      onBackgroundResponseQueued: Symbol('onBackgroundResponseQueued'),
      onBackgroundResponseCompleted: Symbol('onBackgroundResponseCompleted'),
      onBackgroundResponseFailed: Symbol('onBackgroundResponseFailed'),
    },
    useChatStore,
    setReasoningMetaForMessage: () => {},
  })

  handlers.get('onProviderToolStatus')({
    type: 'tool-input-start',
    turnId: 'turn-3',
    toolCallId: 'call-3',
    toolName: 'read',
    toolInput: { path: 'pdfa_checker.py' },
  })
  handlers.get('onProviderToolOutput')({
    turnId: 'turn-3',
    toolCallId: 'call-3',
    toolName: 'read',
    toolInput: { path: 'pdfa_checker.py' },
    output: { success: { path: 'pdfa_checker.py' } },
  })

  assert.equal(activities.length, 2)
  assert.equal(activities[0].id, 'provider_tool:turn-3:call-3')
  assert.equal(activities[0].stepId, 'call-3')
  assert.deepEqual(activities[0].toolInput, { path: 'pdfa_checker.py' })
  assert.equal(activities[1].id, 'provider_tool:turn-3:call-3')
  assert.equal(activities[1].stepId, 'call-3')
})
