import test from 'node:test'
import assert from 'node:assert/strict'
import fs from 'node:fs'
import path from 'node:path'

function readSource(relPath) {
  return fs.readFileSync(path.resolve(relPath), 'utf8')
}

test('App lazy-loads non-chat panels behind suspense fallbacks', () => {
  const appSource = readSource('src/renderer/App.jsx')

  assert.match(appSource, /function scheduleIdleWarmup\(callback, timeout = 600\)/)
  assert.match(appSource, /const loadEditorPanel = \(\) => import\('\.\/components\/EditorPanel\.jsx'\)/)
  assert.match(appSource, /const loadArtifactsPanel = \(\) => import\('\.\/components\/ArtifactsPanel\.jsx'\)/)
  assert.match(appSource, /const loadMemoryPanel = \(\) => import\('\.\/components\/MemoryPanel\.jsx'\)/)
  assert.match(appSource, /const loadSettingsPanel = \(\) => import\('\.\/components\/SettingsPanel\.jsx'\)/)
  assert.match(appSource, /scheduleIdleWarmup\(\(\) => \{ void loadEditorPanel\(\) \}, 120\)/)
  assert.match(appSource, /scheduleIdleWarmup\(\(\) => \{ void loadArtifactsPanel\(\) \}, 220\)/)
  assert.match(appSource, /scheduleIdleWarmup\(\(\) => \{ void loadMemoryPanel\(\) \}, 340\)/)
  assert.match(appSource, /scheduleIdleWarmup\(\(\) => \{ void loadSettingsPanel\(\) \}, 460\)/)
  assert.doesNotMatch(appSource, /loadThreadDrawer|ThreadDrawerLazy|<ThreadDrawer/)
  assert.match(appSource, /const EditorPanelLazy = lazy\(loadEditorPanel\)/)
  assert.match(appSource, /const ArtifactsPanelLazy = lazy\(loadArtifactsPanel\)/)
  assert.match(appSource, /const MemoryPanelLazy = lazy\(loadMemoryPanel\)/)
  assert.match(appSource, /const SettingsPanelLazy = lazy\(loadSettingsPanel\)/)
  assert.match(appSource, /const AgentNavigatorPanelLazy = lazy\(loadAgentNavigatorPanel\)/)
  assert.match(appSource, /import ChatCompanionShell from '\.\/components\/chat\/ChatCompanionShell\.jsx'/)
  assert.match(appSource, /import WorkspaceRail from '\.\/components\/workspace\/WorkspaceRail\.jsx'/)
  assert.match(appSource, /const chatPanelActive = activePanel === 'chat' \|\| !activePanel/)
  assert.match(appSource, /<WorkspaceRail[\s\S]*enabled=\{chatPanelActive\}/)
  assert.match(appSource, /<ChatPanel[\s\S]*workspaceRailEnabled/)
  assert.match(appSource, /activePanel !== 'chat' && \(/)
  assert.match(appSource, /renderOtherPanel\(\)/)
  assert.match(appSource, /const panelLabels = React\.useMemo\(\(\) => getPanelLabels\(t\), \[t\]\)/)
  assert.match(appSource, /WorkspacePanelSkeleton panelLabel=\{panelLabels\.editor\}/)
  assert.match(appSource, /WorkspacePanelSkeleton panelLabel=\{panelLabels\.artifacts\}/)
  assert.match(appSource, /WorkspacePanelSkeleton panelLabel=\{panelLabels\.memory\}/)
  assert.match(appSource, /WorkspacePanelSkeleton panelLabel=\{panelLabels\.settings\}/)
  assert.match(appSource, /WorkspacePanelSkeleton panelLabel=\{panelLabels\.agents\} compact/)
  assert.match(appSource, /<ChatCompanionShell[\s\S]*activeCompanion=\{activeChatCompanion\}[\s\S]*visible=\{chatCompanionVisible\}/)
  assert.match(appSource, /activeChatCompanion === CHAT_COMPANION_AGENTS/)
  assert.match(appSource, /<EditorPanelLazy \/>/)
  assert.match(appSource, /<ArtifactsPanelLazy \/>/)
  assert.match(appSource, /<MemoryPanelLazy \/>/)
  assert.match(appSource, /<SettingsPanelLazy \/>/)
  assert.match(appSource, /<AgentNavigatorPanelLazy embeddedInCompanion \/>/)
  assert.equal(fs.existsSync(path.resolve('src/renderer/components/ThreadDrawer.jsx')), false)
  assert.doesNotMatch(readSource('src/renderer/workspace-panel-loaders.mjs'), /ThreadDrawer/)
})

test('Monaco runtime eagerly initializes the full Monaco instance for instant editor readiness', () => {
  const monacoSetupSource = readSource('src/renderer/monaco-setup.js')
  const mainSource = readSource('src/renderer/main.jsx')
  const monacoLoadGuardSource = readSource('src/renderer/components/editor/MonacoLoadGuard.jsx')
  const editorSurfaceSource = readSource('src/renderer/components/editor/EditorMonacoSurface.jsx')
  const composerSurfaceSource = readSource('src/renderer/components/chat/ComposerCodeBlockAdvancedEditorSurface.jsx')
  const artifactsPanelSource = readSource('src/renderer/components/ArtifactsPanel.jsx')
  const viteConfigSource = readSource('vite.config.js')

  assert.match(mainSource, /import '\.\/monaco-setup\.js'/)
  assert.match(monacoSetupSource, /import \* as monaco from 'monaco-editor'/)
  assert.match(monacoSetupSource, /configureDiagnostics\(monaco\)/)
  assert.match(monacoSetupSource, /loader\.init\(\)\.catch\(\(\) => \{\}\)/)
  assert.match(monacoSetupSource, /export async function ensureMonacoLanguage\(\)/)
  assert.match(viteConfigSource, /optimizeDeps:\s*\{\s*include:\s*\[/s)
  assert.match(viteConfigSource, /'monaco-editor'/)
  assert.match(monacoLoadGuardSource, /const DEFAULT_MONACO_TIMEOUT_MS = 8000/)
  assert.match(monacoLoadGuardSource, /Editor runtime failed to initialize\. Reload the app\./)
  assert.match(monacoLoadGuardSource, /setTimedOut\(true\)/)
  assert.match(monacoLoadGuardSource, /loadingElement: timedOut \? <MonacoLoadError/)

  assert.doesNotMatch(editorSurfaceSource, /languageReady/)
  assert.doesNotMatch(editorSurfaceSource, /ensureMonacoLanguage\(language\)\.then\(\(\) => \{/)
  assert.match(editorSurfaceSource, /useMonacoLoadGuard/)
  assert.match(editorSurfaceSource, /onMount=\{handleMount\}/)
  assert.match(editorSurfaceSource, /loading=\{loadingElement\}/)
  assert.doesNotMatch(composerSurfaceSource, /languageReady/)
  assert.doesNotMatch(composerSurfaceSource, /ensureMonacoLanguage\(language\)\.then\(\(\) => \{/)
  assert.match(composerSurfaceSource, /useMonacoLoadGuard/)
  assert.match(composerSurfaceSource, /onMount=\{handleMount\}/)
  assert.match(composerSurfaceSource, /loading=\{loadingElement\}/)
  assert.doesNotMatch(artifactsPanelSource, /languageReady/)
  assert.doesNotMatch(artifactsPanelSource, /ensureMonacoLanguage\(language\)\.then\(\(\) => \{/)
  assert.doesNotMatch(artifactsPanelSource, /Loading diff\.\.\./)
  assert.match(artifactsPanelSource, /useMonacoLoadGuard/)
  assert.match(artifactsPanelSource, /Diff runtime failed to initialize\. Reload the app\./)
})

test('SettingsPanelRoot memoizes category and section derivation', () => {
  const source = readSource('src/renderer/components/settings/SettingsPanelRoot.jsx')

  assert.match(source, /const categories = useMemo\(\(\) => buildSettingsCategories\(/)
  assert.match(source, /const categoriesById = useMemo\(\s*\(\) => Object\.fromEntries/)
  assert.match(source, /const activeSections = useMemo\(\(\) => buildActiveSettingsSections\(/)
})

test('ChatPanel, EditorPanel, and stream runtime guard diagnostics behind development flags', () => {
  const chatPanelSource = readSource('src/renderer/components/ChatPanel.jsx')
  const chatComposerDraftStateSource = readSource('src/renderer/components/chat/use-chat-panel-composer-draft-state.mjs')
  const editorPanelSource = readSource('src/renderer/components/EditorPanel.jsx')
  const chatEventBridgeSource = readSource('src/renderer/components/ChatEventBridge.jsx')
  const streamRuntimeSource = readSource('src/renderer/components/chat/chat-event-bridge-stream-runtime.mjs')
  const messageBubbleSource = readSource('src/renderer/components/chat/MessageBubble.jsx')
  const finalAnswerSource = readSource('src/renderer/components/chat/final-document/FinalAnswerDocument.jsx')
  const chatComposerGuardSource = `${chatPanelSource}\n${chatComposerDraftStateSource}`

  assert.match(chatComposerGuardSource, /if \(import\.meta\.env\.DEV\) \{\s*console\.warn\('\[ADDOM chat composer\] failed to parse markdown draft; preserving raw text'/)
  assert.match(chatComposerGuardSource, /if \(import\.meta\.env\.DEV\) \{\s*console\.warn\('\[ADDOM chat composer\] failed to extract blocks from draft text'/)

  assert.match(editorPanelSource, /if \(import\.meta\.env\.DEV\) console\.warn\(`\[editor-format\] \$\{result\.message\}`\)/)
  assert.match(editorPanelSource, /if \(import\.meta\.env\.DEV\) console\.warn\('\[editor-format\] formatText failed', err\)/)
  assert.match(editorPanelSource, /if \(import\.meta\.env\.DEV\) console\.warn\(`\[editor-fix\] \$\{result\.message\}`\)/)
  assert.match(editorPanelSource, /if \(import\.meta\.env\.DEV\) console\.warn\('\[editor-fix\] codeActions failed', err\)/)
  assert.match(editorPanelSource, /if \(import\.meta\.env\.DEV\) console\.warn\(`\[editor-ai-selection\] unavailable: \$\{selection\?\.reason \|\| 'no_selection'\}`\)/)
  assert.doesNotMatch(editorPanelSource, /modelRegistryVersion:\s*s\.modelRegistryVersion/)
  assert.match(editorPanelSource, /previewContentByTabId/)

  assert.match(chatEventBridgeSource, /if \(import\.meta\?\.\s*env\?\.\s*DEV\) \{\s*console\.warn\(`\[ChatEventBridge\] Missing chat subscription API: \$\{name\}`\)/)
  assert.match(chatEventBridgeSource, /if \(import\.meta\?\.\s*env\?\.\s*DEV\) \{\s*console\.warn\(`\[ChatEventBridge\] Failed to subscribe: \$\{name\}`,\s*error\)/)
  assert.match(streamRuntimeSource, /if \(dev && reason === 'immediate'\) \{\s*console\.debug\('\[ChatEventBridge\] stream_flush_immediate'/)
  assert.match(streamRuntimeSource, /if \(dev\) \{\s*console\.info\('\[ChatEventBridge\] stream_metrics', snapshot\)/)
  assert.match(finalAnswerSource, /const CHAT_RENDER_DEBUG = import\.meta\.env\.DEV && import\.meta\.env\.VITE_CHAT_PERF_DEBUG === '1'/)
  assert.match(finalAnswerSource, /if \(!CHAT_RENDER_DEBUG \|\| !block\?\.id\) return undefined/)
  assert.doesNotMatch(messageBubbleSource, /parseChatRenderSegments|segmentCacheRef/)
  assert.match(streamRuntimeSource, /const buffer = getOrCreateChannelBuffer\(\s*isReasoning\s*\?\s*reasoningBufferByMessageId\s*:\s*\(isExecutionText \? executionBufferByMessageId : textBufferByMessageId\),\s*targetId,\s*\)/)
  assert.match(streamRuntimeSource, /scheduleBufferedChannelFlush\(targetId, channel\)/)
  assert.doesNotMatch(messageBubbleSource, /useDeferredValue\(/)
  assert.doesNotMatch(messageBubbleSource, /useStreamingRenderText\(/)
})

test('internal troubleshooting surfaces are gated behind development builds', () => {
  const writeConflictSource = readSource('src/renderer/components/chat/WriteConflictCard.jsx')
  const settingsCommonSource = readSource('src/renderer/components/settings/SettingsCommonBlocks.jsx')
  const commandSafetySource = readSource('src/renderer/components/settings/SettingsCommandSafetyBlock.jsx')
  const governanceSource = readSource('src/renderer/components/settings/SettingsBlocksGovernance.jsx')
  const settingsSectionsSource = readSource('src/renderer/components/settings/SettingsPanelSections.jsx')

  assert.match(writeConflictSource, /const SHOW_DEV_CONFLICT_DEBUG = import\.meta\.env\.DEV/)
  assert.match(writeConflictSource, /SHOW_DEV_CONFLICT_DEBUG \? \(\s*<button[\s\S]*showDebugInfo/)
  assert.match(writeConflictSource, /SHOW_DEV_CONFLICT_DEBUG && showDiffs && \(/)

  assert.match(settingsCommonSource, /const SHOW_DEV_SETTINGS_SURFACES = import\.meta\.env\.DEV/)
  assert.doesNotMatch(settingsCommonSource, /ExecutionTimelineBlock/)
  assert.match(settingsCommonSource, /SHOW_DEV_SETTINGS_SURFACES && selectedLocaleIsValidationOnly/)
  assert.match(settingsCommonSource, /SHOW_DEV_SETTINGS_SURFACES && selectedLocaleIsSavedOnly/)

  assert.doesNotMatch(commandSafetySource, /SandboxBlock/)
  assert.doesNotMatch(commandSafetySource, /AdvancedSafetyBlock/)
  assert.doesNotMatch(commandSafetySource, /Advanced diagnostics/)
  assert.doesNotMatch(commandSafetySource, /Install sandbox backend/)

  assert.doesNotMatch(governanceSource, /EditorAssistBlock/)
  assert.doesNotMatch(governanceSource, /ComplianceBlock/)
  assert.doesNotMatch(governanceSource, /ContinuityPolicyBlock/)

  assert.doesNotMatch(settingsSectionsSource, /const SHOW_DEV_SETTINGS_SURFACES = import\.meta\.env\.DEV/)
  assert.doesNotMatch(settingsSectionsSource, /id: 'execution-timeline'/)
  assert.doesNotMatch(settingsSectionsSource, /id: 'advanced-settings'/)
  assert.doesNotMatch(settingsSectionsSource, /case 'memory_continuity'/)
  assert.doesNotMatch(settingsSectionsSource, /case 'moa'/)
  assert.equal(fs.existsSync(path.resolve('src/renderer/components/settings/ContinuityPolicySection.jsx')), false)
  assert.equal(fs.existsSync(path.resolve('src/renderer/components/settings/use-settings-panel-command-safety.mjs')), false)
})

test('ChatEventBridge uses the canonical Agent Run bridge without legacy MoA hydration', () => {
  const source = readSource('src/renderer/components/ChatEventBridge.jsx')

  assert.match(source, /registerAgentRunEventBridge/)
  assert.doesNotMatch(source, /useMoaStore|registerMoaTimelineHydration|registerMoaEventBridgeHandlers/)
  assert.equal(fs.existsSync(path.resolve('src/renderer/store/useMoaStore.js')), false)
})

test('legacy ThreadDrawer has no file, loader, import, render, or hidden fallback', () => {
  const source = `${readSource('src/renderer/App.jsx')}\n${readSource('src/renderer/workspace-panel-loaders.mjs')}`
  assert.equal(fs.existsSync(path.resolve('src/renderer/components/ThreadDrawer.jsx')), false)
  assert.doesNotMatch(source, /ThreadDrawer|threadDrawerOpen/)
})

test('main and child conversations share timeline measurement and virtualization machinery', () => {
  const source = readSource('src/renderer/components/chat/ChatPanelTimelineArea.jsx')
  const agentSource = readSource('src/renderer/components/agents/AgentConversationView.jsx')
  const virtualizationSource = readSource('src/renderer/components/chat/chat-timeline-virtualization.mjs')
  const virtualizationReactSource = readSource('src/renderer/components/chat/use-timeline-virtualization.jsx')
  const liveExecutionSource = readSource('src/renderer/components/chat/LiveExecutionStreamBlock.jsx')
  const reasoningSource = readSource('src/renderer/components/chat/live-execution-stream-reasoning.jsx')
  const assistantRichContentSource = readSource('src/renderer/components/chat/AssistantRichContent.jsx')
  const richRendererSource = readSource('src/renderer/components/chat/chat-rich-content-renderer.jsx')

  assert.match(virtualizationSource, /TIMELINE_BLOCK_ESTIMATED_HEIGHT_PX = 196/)
  assert.match(virtualizationSource, /TIMELINE_BLOCK_OVERSCAN = 4/)
  assert.match(virtualizationSource, /TIMELINE_BLOCK_VIRTUALIZE_MIN_COUNT = 40/)
  assert.match(virtualizationSource, /TIMELINE_VIRTUALIZATION_MAX_MOUNTED_BLOCKS = 60/)
  assert.match(virtualizationSource, /function findFirstBlockEndingAfter/)
  assert.match(virtualizationSource, /export function resolveTimelineAnchorCorrection/)
  assert.match(virtualizationReactSource, /function TimelineMeasuredBlock\(/)
  assert.match(virtualizationReactSource, /const containsExecutionStream = node\.querySelector\('\[data-live-execution-stream-root="true"\]'\) !== null/)
  assert.match(virtualizationReactSource, /new ResizeObserver\(\(\) => \{\s*measureNow\(\)\s*\}\)/s)
  assert.match(virtualizationReactSource, /const shouldTrackScrollMetrics = timelineBlocks\.length >= TIMELINE_BLOCK_VIRTUALIZE_MIN_COUNT/)
  assert.match(virtualizationReactSource, /const renderedBlockEntries = virtualizationEnabled/)
  assert.match(source, /useTimelineVirtualization\(\{/)
  assert.match(agentSource, /useTimelineVirtualization\(\{/)
  assert.doesNotMatch(agentSource, /agent-conversation-load-more|Load more activity/)
  assert.match(source, /return wrapTimelineBlock\(blockKey, blockId,/)
  assert.match(source, /onScroll=\{scrollHandlers\.onScroll\}/)
  assert.match(liveExecutionSource, /data-live-execution-stream-root="true"/)
  assert.match(reasoningSource, /import AssistantRichContent from '\.\/AssistantRichContent\.jsx'/)
  assert.doesNotMatch(reasoningSource, /useReasoningMarkdownEnvironment/)
  assert.doesNotMatch(reasoningSource, /ReasoningCodeBlock/)
  assert.match(assistantRichContentSource, /parseChatRenderSegments\(/)
  assert.match(assistantRichContentSource, /mode = 'assistant-message'/)
  assert.match(assistantRichContentSource, /useChatMarkdownComponents\(\{/)
  assert.match(assistantRichContentSource, /renderChatRichContentSegments\(/)
  assert.match(richRendererSource, /export function useChatMarkdownComponents/)
  assert.match(reasoningSource, /if \(item\.hasPendingTail\) \{/)
  assert.match(reasoningSource, /previousReasoningDetailEndsWithConnector/)
  assert.equal(fs.existsSync(path.resolve('src/renderer/components/chat/ReasoningBlock.jsx')), false)
  assert.equal(fs.existsSync(path.resolve('src/renderer/components/chat/reasoning-segment-parser.mjs')), false)
  assert.equal(fs.existsSync(path.resolve('src/renderer/components/chat/reasoning-block-view-model.mjs')), false)
})

test('final answers use a dedicated faithful renderer while execution content keeps shared rich primitives', () => {
  const richRendererSource = readSource('src/renderer/components/chat/chat-rich-content-renderer.jsx')
  const assistantRichContentSource = readSource('src/renderer/components/chat/AssistantRichContent.jsx')
  const messageBubbleSource = readSource('src/renderer/components/chat/MessageBubble.jsx')
  const finalAnswerSource = readSource('src/renderer/components/chat/final-document/FinalAnswerDocument.jsx')
  const finalComponentsSource = readSource('src/renderer/components/chat/final-document/final-answer-markdown-components.jsx')
  const reasoningSource = readSource('src/renderer/components/chat/live-execution-stream-reasoning.jsx')
  const activitySource = readSource('src/renderer/components/chat/live-execution-stream-activity.jsx')

  assert.match(richRendererSource, /const CHAT_RICH_CONTENT_FEATURE_MODE_DEFAULTS = \{/)
  assert.match(richRendererSource, /'execution-stream': \{\s*allowPatchFileGroups: false,\s*allowDispatchCards: false,\s*allowCouncilCards: false,\s*allowReviewCards: false,\s*\}/s)
  assert.match(richRendererSource, /'assistant-message': \{\s*allowPatchFileGroups: false,\s*allowDispatchCards: false,\s*allowCouncilCards: false,\s*allowReviewCards: false,\s*\}/s)
  assert.doesNotMatch(richRendererSource, /allowRoleCards|tryParseRoleJson|renderRoleConfirmationCard/)
  assert.match(richRendererSource, /if \(!resolvedFeaturePolicy\.allowPatchFileGroups\)/)
  assert.match(richRendererSource, /if \(hasDelegationPayload\(segmentText\)\)/)
  assert.match(richRendererSource, /Legacy markers and compact .* are suppressed/)
  assert.doesNotMatch(richRendererSource, /allowDelegationCards/)
  assert.doesNotMatch(richRendererSource, /<DelegationResultsCard/)
  assert.match(assistantRichContentSource, /renderChatRichContentSegments\(segments, \{\s*keyPrefix,\s*mode,\s*featurePolicy,/s)
  assert.match(messageBubbleSource, /import FinalAnswerDocument from '\.\/final-document\/FinalAnswerDocument\.jsx'/)
  assert.match(
    messageBubbleSource,
    /<FinalAnswerDocument\s+text=\{canonicalFinalText\}\s+messageId=\{message\.id\}\s+threadId=\{message\?\.streamMeta\?\.threadId\}\s+isStreaming=\{isStreaming\}\s+generatedArtifacts=\{message\.generatedArtifacts\}/s,
  )
  assert.match(finalAnswerSource, /data-final-answer-document="true"/)
  assert.match(finalAnswerSource, /projectStreamingFinalDocument\(/)
  assert.match(finalComponentsSource, /data-final-answer-table-scroll="true"/)
  assert.doesNotMatch(finalAnswerSource, /parseChatRenderSegments|groupPatchSegments|record_list/)
  assert.doesNotMatch(finalComponentsSource, /parseChatRenderSegments|groupPatchSegments|record_list|reference_table/)

  assert.match(reasoningSource, /import AssistantRichContent from '\.\/AssistantRichContent\.jsx'/)
  assert.match(activitySource, /import AssistantRichContent from '\.\/AssistantRichContent\.jsx'/)
  assert.doesNotMatch(reasoningSource, /DelegationResultsCard|PatchFileGroup|CodeSnippetBlock|DiffCodeBlock|MemoProseMarkdown/)
  assert.doesNotMatch(activitySource, /DelegationResultsCard|PatchFileGroup|CodeSnippetBlock|DiffCodeBlock|MemoProseMarkdown/)
})

test('chat markdown runtime is lazy-loaded off the default chat path', () => {
  const globalsSource = readSource('src/renderer/styles/globals.css')
  const messageBubbleSource = readSource('src/renderer/components/chat/MessageBubble.jsx')
  const bubbleUtilsSource = readSource('src/renderer/components/chat/message-bubble-render-utils.mjs')
  const assistantRichContentSource = readSource('src/renderer/components/chat/AssistantRichContent.jsx')
  const reasoningSource = readSource('src/renderer/components/chat/live-execution-stream-reasoning.jsx')
  const lazyRuntimeSource = readSource('src/renderer/components/markdown/LazyMarkdownRenderer.jsx')
  const clientRuntimeSource = readSource('src/renderer/components/markdown/MarkdownRuntimeClient.jsx')

  assert.doesNotMatch(globalsSource, /highlight\.js\/styles\/github-dark\.css/)
  assert.doesNotMatch(messageBubbleSource, /import ReactMarkdown from 'react-markdown'/)
  assert.doesNotMatch(messageBubbleSource, /markdown-plugin-config/)
  assert.doesNotMatch(bubbleUtilsSource, /import ReactMarkdown from 'react-markdown'/)
  assert.doesNotMatch(assistantRichContentSource, /markdown-plugin-config/)
  assert.doesNotMatch(reasoningSource, /markdown-plugin-config/)
  assert.match(lazyRuntimeSource, /const LazyClientMarkdownContent = React\.lazy\(async \(\) =>/)
  assert.match(lazyRuntimeSource, /clientMarkdownRuntimePromise = import\('\.\/MarkdownRuntimeClient\.jsx'\)/)
  assert.match(lazyRuntimeSource, /await import\('\.\/MarkdownRuntimeServer\.jsx'\)/)
  assert.match(clientRuntimeSource, /highlight-theme\.css/)
})

test('ChatPanel memoizes canonical and windowed timeline derivation to avoid churn on composer-only renders', () => {
  const chatPanelSource = readSource('src/renderer/components/ChatPanel.jsx')
  const helpersSource = readSource('src/renderer/components/chat/chat-panel-helpers.mjs')

  assert.match(chatPanelSource, /const visibleTimeline = useMemo\(\(\) => timeline, \[timeline\]\)/)
  assert.doesNotMatch(chatPanelSource, /message\?\.status === 'streaming'/)
  assert.match(chatPanelSource, /const renderedTimeline = useMemo\(\s*\(\) => \(hiddenTimelineCount > 0/)
  assert.match(chatPanelSource, /const timelineTurnIndex = useMemo\(\s*\(\) => buildTimelineTurnIndex\(visibleTimeline\)/)
  assert.match(chatPanelSource, /buildTimelineBlocksWithMeta\(renderedTimeline, \{ turnIndex: timelineTurnIndex \}\)/)
  assert.match(helpersSource, /export function buildTimelineTurnIndex\(sourceTimeline = \[\]\)/)
  assert.match(helpersSource, /fileChangesByTurn\.set\(turnId, collectTurnFileChanges\(activities\)\)/)
  assert.match(chatPanelSource, /\[hiddenTimelineCount, visibleTimeline\],/)
})

test('chat composer hot path uses cheap draft metadata and memoized sibling subtrees', () => {
  const chatPanelSource = [
    readSource('src/renderer/components/ChatPanel.jsx'),
    readSource('src/renderer/components/chat/ChatPanelView.jsx'),
  ].join('\n')
  const draftStateSource = readSource('src/renderer/components/chat/use-chat-panel-composer-draft-state.mjs')
  const composerAreaSource = readSource('src/renderer/components/chat/ChatPanelComposerArea.jsx')
  const composerSource = readSource('src/renderer/components/chat/ChatComposer.jsx')
  const draftTextareaSource = readSource('src/renderer/components/chat/ChatComposerDraftTextarea.jsx')
  const timelineAreaSource = readSource('src/renderer/components/chat/ChatPanelTimelineArea.jsx')
  const railSource = readSource('src/renderer/components/chat/ChatComposerControlRail.jsx')
  const composerActionsSource = readSource('src/renderer/components/chat/use-chat-panel-composer-actions.mjs')
  const perfDebugSource = readSource('src/renderer/components/chat/use-chat-panel-perf-debug.mjs')

  assert.match(draftStateSource, /export function hasTripleBacktickFenceCandidate\(value = ''\)/)
  assert.match(draftStateSource, /if \(!hasTripleBacktickFenceCandidate\(rawNext\)\) \{/)
  assert.match(draftStateSource, /usedFenceParsing: false/)
  assert.match(draftStateSource, /export function deriveComposerDraftMetadata\(/)
  assert.match(draftStateSource, /const \[composerDraftSyncVersion, setComposerDraftSyncVersion\] = useState\(0\)/)
  assert.match(draftStateSource, /const \[composerBlocksSyncVersion, setComposerBlocksSyncVersion\] = useState\(0\)/)
  assert.match(draftStateSource, /const scheduleComposerDraftPersist = useCallback\(\(\) => \{/)
  assert.match(draftStateSource, /syncExternalBlocks: options\.syncExternalBlocks === true/)
  assert.match(draftStateSource, /setComposerBlocksSyncVersion\(\(prev\) => prev \+ 1\)/)
  assert.match(draftStateSource, /syncExternalDraftText: false/)
  assert.match(draftStateSource, /return nextSnapshot\.draftText/)
  assert.doesNotMatch(draftStateSource, /\[activeThreadId, composerBlocks, composerDraftText\]/)

  assert.doesNotMatch(chatPanelSource, /const composerSerializedDraft = useMemo\(/)
  assert.match(chatPanelSource, /&& \(hasComposerContent \|\| attachedImages.length > 0\)/)
  assert.match(chatPanelSource, /\|\| isDirectAgentDraft/)
  assert.match(chatPanelSource, /MemoChatPanelTimelineArea as ChatPanelTimelineArea/)
  assert.match(chatPanelSource, /useChatPanelPerfDebug\(\{ composerDraftText \}\)/)
  assert.match(perfDebugSource, /const devPerfEnabled = import\.meta\.env\.DEV && import\.meta\.env\.VITE_CHAT_PERF_DEBUG === '1'/)
  assert.match(chatPanelSource, /composerDraftSyncVersion=\{composerDraftSyncVersion\}/)
  assert.match(chatPanelSource, /composerBlocksSyncVersion=\{composerBlocksSyncVersion\}/)

  assert.match(composerSource, /import\s+ChatComposerDraftTextarea\s+from\s+'\.\/ChatComposerDraftTextarea\.jsx'/)
  assert.match(composerSource, /import\s+\{\s*applyCodeBlockKeymap\s*\}\s+from\s+'\.\/composer-code-keymap\.mjs'/)
  assert.match(composerSource, /<ChatComposerDraftTextarea/)
  assert.match(composerSource, /const \[liveComposerBlocks, setLiveComposerBlocks\] = React\.useState/)
  assert.match(composerSource, /const MemoChatComposerCodeBlockRow = React\.memo\(ChatComposerCodeBlockRow\)/)
  assert.match(composerSource, /const MemoChatComposerTextBlockRow = React\.memo\(ChatComposerTextBlockRow\)/)
  assert.match(composerSource, /const deferredCode = React\.useDeferredValue\(String\(block\.code \|\| ''\)\)/)
  assert.match(composerSource, /const \[highlightHtml, setHighlightHtml\] = React\.useState\(null\)/)
  assert.match(composerSource, /scheduleComposerHighlightWork/)
  assert.match(composerSource, /commitLocalBlocks\(nextBlocks, \{ source: 'text_block' \}\)/)
  assert.match(composerSource, /commitLocalBlocks\(nextBlocks, \{ source: 'code_block' \}\)/)
  assert.match(composerSource, /commitLocalBlocks\(nextBlocks, \{ source: 'code_block_keymap' \}\)/)
  assert.match(draftTextareaSource, /const \[draftText, setDraftText\] = React\.useState/)
  assert.match(draftTextareaSource, /setDraftText\(String\(composerDraftText \|\| ''\)\)/)
  assert.match(draftTextareaSource, /const \[layout, setLayout\] = React\.useState\(\(\) => \(\{/)
  assert.match(draftTextareaSource, /const contentHeight = Math\.max\(minHeight, Math\.ceil\(Number\(node\.scrollHeight\) \|\| 0\)\)/)
  assert.match(draftTextareaSource, /const nextShouldScroll = contentHeight > nextHeight/)
  assert.match(draftTextareaSource, /React\.useLayoutEffect\(\(\) => \{\s*measureLayout\(\)\s*\}, \[measureLayout, draftText\]\)/s)
  assert.match(draftTextareaSource, /const observer = new ResizeObserver\(\(\) => \{\s*measureLayout\(\)\s*\}\)/s)
  assert.match(draftTextareaSource, /rows=\{1\}/)
  assert.match(draftTextareaSource, /setDraftText\(rawNext\)/)
  assert.match(draftTextareaSource, /const MemoChatComposerDraftTextarea = React\.memo\(ChatComposerDraftTextarea\)/)
  assert.match(timelineAreaSource, /const MemoChatPanelTimelineArea = React\.memo\(ChatPanelTimelineArea\)/)
  assert.match(railSource, /const MemoChatComposerControlRail = React\.memo\(ChatComposerControlRail\)/)
  assert.match(composerAreaSource, /MemoChatComposerControlRail as ChatComposerControlRail/)
  assert.match(composerAreaSource, /composerBlocksSyncVersion/)
  assert.match(readSource('src/renderer/components/chat/use-chat-composer-resize.mjs'), /const MIN_PERSISTED_DRAFT_TEXTAREA_MAX_HEIGHT = DEFAULT_DRAFT_TEXTAREA_MAX_HEIGHT/)
  assert.doesNotMatch(composerActionsSource, /applyCodeBlockKeymap/)
})

test('EditorPanel suppresses optional formatter and fixer availability warnings while keeping real degraded failures visible', () => {
  const editorPanelSource = readSource('src/renderer/components/EditorPanel.jsx')
  const editorPanelStateSource = readSource('src/renderer/components/editor/editor-panel-state-helpers.mjs')
  const editorPanelViewSource = readSource('src/renderer/components/editor/EditorPanelView.jsx')
  const helperSource = readSource('src/renderer/components/editor/editor-setup-hints.mjs')
  const diagnosticsSource = readSource('src/renderer/components/editor/EditorDiagnosticsPanels.jsx')
  const tabBarSource = readSource('src/renderer/components/editor/EditorTabBar.jsx')

  assert.match(editorPanelStateSource, /const OPTIONAL_EDITOR_SERVICE_WARNING_PROVIDER_IDS = new Set\(\[/)
  assert.match(editorPanelStateSource, /'biome'/)
  assert.match(editorPanelStateSource, /'eslint'/)
  assert.match(editorPanelStateSource, /'clang-format'/)
  assert.match(editorPanelStateSource, /'clang-tidy'/)
  assert.match(editorPanelStateSource, /'csharpier'/)
  assert.match(editorPanelStateSource, /'dotnet-format'/)
  assert.match(editorPanelStateSource, /'ruff'/)
  assert.match(editorPanelStateSource, /function getActionableServiceNotice\(serviceState = null\)/)
  assert.match(editorPanelStateSource, /return serviceState/)
  assert.match(editorPanelSource, /const currentLanguageServiceNotice = useMemo\(\(\) => buildLocalizedEditorServiceNotice\(\{/)
  assert.match(editorPanelSource, /optionalUnavailableProviderIds: OPTIONAL_EDITOR_SERVICE_WARNING_PROVIDER_IDS/)
  assert.match(editorPanelSource, /buildEditorCapabilityActionTitle/)
  assert.match(editorPanelSource, /buildEditorSetupHints/)
  assert.match(editorPanelSource, /readDismissedEditorSetupHintIds/)
  assert.match(editorPanelSource, /writeDismissedEditorSetupHintIds/)
  assert.match(editorPanelSource, /const \[dismissedSetupHintIds, setDismissedSetupHintIds\] = useState\(readDismissedEditorSetupHintIds\)/)
  assert.match(editorPanelSource, /const currentSetupHints = useMemo\(\(\) => buildEditorSetupHints\(\{/)
  assert.match(editorPanelSource, /const formatActionTitle = useMemo\(\(\) => buildEditorCapabilityActionTitle\(\{/)
  assert.match(editorPanelSource, /const fixActionTitle = useMemo\(\(\) => buildEditorCapabilityActionTitle\(\{/)
  assert.match(editorPanelSource, /const dismissSetupHint = useCallback\(\(hint\) => \{/)
  assert.match(editorPanelSource, /writeDismissedEditorSetupHintIds\(next\)/)
  assert.match(editorPanelViewSource, /formatActionTitle=\{formatActionTitle\}/)
  assert.match(editorPanelViewSource, /fixActionTitle=\{fixActionTitle\}/)
  assert.match(editorPanelViewSource, /setupHints=\{currentSetupHints\}/)
  assert.match(editorPanelViewSource, /onDismissSetupHint=\{dismissSetupHint\}/)

  assert.match(helperSource, /const ACTIONABLE_SETUP_REASONS = new Set\(\[/)
  assert.match(helperSource, /'prettier_not_installed'/)
  assert.match(helperSource, /'ruff_not_installed'/)
  assert.match(helperSource, /'clang_format_not_installed'/)
  assert.match(helperSource, /'clang_tidy_not_installed'/)
  assert.match(helperSource, /'csharpier_not_installed'/)
  assert.match(helperSource, /'dotnet_format_not_installed'/)
  assert.match(helperSource, /'dotnet_not_installed'/)
  assert.match(helperSource, /'eslint-project-config': \{/)
  assert.match(helperSource, /label: 'ESLint'/)
  assert.match(helperSource, /'smol-toml': \{/)
  assert.match(helperSource, /function inferProviderFromMessage/)
  assert.match(helperSource, /if \(\/eslint\/i\.test\(text\)\) return PROVIDER_METADATA\['eslint-project-config'\]/)
  assert.match(helperSource, /export function buildEditorCapabilityActionTitle/)
  assert.match(helperSource, /export function buildEditorSetupHints/)
  assert.match(helperSource, /const EDITOR_SETUP_HINT_DISMISSALS_STORAGE_KEY = 'addom\.editor\.setupHints\.dismissed'/)

  assert.match(diagnosticsSource, /setupHints = \[\]/)
  assert.match(diagnosticsSource, /onDismissSetupHint/)
  assert.match(diagnosticsSource, /visibleSetupHints\.length > 0/)
  assert.match(diagnosticsSource, /editor\.diagnostics\.outline\.setupTitle[\s\S]*defaultValue: 'Setup'/s)
  assert.match(diagnosticsSource, /editor\.panel\.dismiss[\s\S]*defaultValue: 'Dismiss'/s)

  assert.match(tabBarSource, /formatActionTitle = 'Format document with the active formatter route \(Shift\+Alt\+F\)'/)
  assert.match(tabBarSource, /fixActionTitle = 'Apply auto-fixable issues from the active code-action provider'/)
  assert.match(tabBarSource, /title=\{fixActionTitle\}/)
  assert.match(tabBarSource, /title=\{formatActionTitle\}/)
})
